// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cart struct {
	ID       int    `json:"id"`
	Sku      string `json:"sku"`
	Quantity int    `json:"quantity"`
}

type Carts struct {
	Edges    []*Cart   `json:"edges"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type CheckOutItem struct {
	Contents []*NewCart `json:"contents"`
}

type NewCart struct {
	Sku      string `json:"sku"`
	Quantity int    `json:"quantity"`
}

type NewProduct struct {
	Sku      string  `json:"sku"`
	Name     string  `json:"name"`
	Price    float64 `json:"price"`
	Quantity int     `json:"quantity"`
}

type NewPromo struct {
	Sku              string  `json:"sku"`
	PromoType        string  `json:"promoType"`
	MinimalPurchased int     `json:"minimalPurchased"`
	BonusProductSku  string  `json:"bonusProductSku"`
	Discount         float64 `json:"discount"`
	IsActive         bool    `json:"isActive"`
}

type PageInfo struct {
	After     int `json:"after"`
	Before    int `json:"before"`
	TotalPage int `json:"totalPage"`
	Page      int `json:"page"`
}

type PagingQuery struct {
	Page  int `json:"page"`
	Limit int `json:"limit"`
}

type Product struct {
	ID       int     `json:"id"`
	Sku      string  `json:"sku"`
	Name     string  `json:"name"`
	Price    float64 `json:"price"`
	Quantity int     `json:"quantity"`
}

type Products struct {
	Edges    []*Product `json:"edges"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type Promo struct {
	ID               int     `json:"id"`
	Sku              string  `json:"sku"`
	PromoType        string  `json:"promoType"`
	MinimalPurchased int     `json:"minimalPurchased"`
	BonusProductSku  string  `json:"bonusProductSku"`
	Discount         float64 `json:"discount"`
	IsActive         bool    `json:"isActive"`
}

type Promos struct {
	Edges    []*Promo  `json:"edges"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type ResponseCheckout struct {
	Total float64 `json:"total"`
}
