// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cart struct {
	ID       int    `json:"id"`
	Sku      string `json:"sku"`
	Quantity int    `json:"quantity"`
}

type Carts struct {
	Contents []*NewCart `json:"contents"`
}

type NewCart struct {
	Sku      string `json:"sku"`
	Quantity int    `json:"quantity"`
}

type NewProduct struct {
	Sku      string  `json:"sku"`
	Name     string  `json:"name"`
	Price    float64 `json:"price"`
	Quantity int     `json:"quantity"`
}

type NewPromo struct {
	Sku              string  `json:"sku"`
	PromoType        string  `json:"promoType"`
	MinimalPurchased int     `json:"minimalPurchased"`
	BonusProductSku  string  `json:"bonusProductSku"`
	Discount         float64 `json:"discount"`
}

type Product struct {
	ID       int     `json:"id"`
	Sku      string  `json:"sku"`
	Name     string  `json:"name"`
	Price    float64 `json:"price"`
	Quantity int     `json:"quantity"`
}

type Promo struct {
	ID               int     `json:"id"`
	Sku              string  `json:"sku"`
	PromoType        string  `json:"promoType"`
	MinimalPurchased int     `json:"minimalPurchased"`
	BonusProductSku  string  `json:"bonusProductSku"`
	Discount         float64 `json:"discount"`
}

type ResponseCheckout struct {
	Total float64 `json:"total"`
}

type ResponseCreated struct {
	ID int `json:"id"`
}

type ResponseUpdated struct {
	Status string `json:"status"`
}
